[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "true"
  NETLIFY_BUILD_SKIP = "false"

[build.processing]
  skip_processing = false

[dev]
  command = "vite"
  port = 3000
  publish = "dist"

  publish = "dist"